extends: [airbnb-base, plugin:prettier/recommended]
env:
  es2023: true
  node: true
parserOptions:
  ecmaVersion: 2023
  sourceType: module
rules:
  no-console: off
  import/prefer-default-export: off
