name: Check project standards

on: push

jobs:
  check-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install
      - run: npm exec prettier -- --check "**/*.{js,json,yml}"
      - run: npm exec eslint -- "**/*.js"
      - run: npm exec tsc
